[package]
name = "bytebit/server-networked-values"
description = "A library for networking persistent values from the server to the client for Roblox development written using roblox-ts."
version = "0.0.15"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
